version: '3.8'

#x-common-variables:
#  &db-env-vars
#     POSTGRES_DB: books_db
#     POSTGRES_USER: root
#     POSTGRES_PASSWORD: qwerty

services:
  jira:
    container_name: app-jira
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_jira:5432/books_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=qwerty
    #      - POSTGRES_USER= root
    #      - POSTGRES_PASSWORD= qwerty
    #      - POSTGRES_DB= books_db
    #      - POSTGRES_HOST= jdbc:postgresql://localhost
    #      - POSTGRES_PORT= 15432
    depends_on:
      postgres_jira:
        condition: service_healthy
      nginx:
        condition: service_healthy

  postgres_jira:
    container_name: db-postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "15432:5432"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres-data:



